spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            # This matches the URI you set in the Google Cloud Console
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 500ms

      lettuce:
        pool:
          max-active: 200
          max-idle: 50
          min-idle: 10
          max-wait: 100ms

# Server configuration
server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 604800000
frontend:
  url: "http://localhost:3000"
interview:
  duration: 150
submission:
  judging:
    executor:
      pool-size: 5
judge:
  execution:
    url: http://127.0.0.1:2000/api/v2/execute
