import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { config } from './config.ts'

const ASSETS_DIR = join(config.dataDir, 'assets')

/** Asset ids are generated by the client (`<uniqueId>-<file name>`), sanitized to a safe file name. */
export const ASSET_ID_PATTERN = /^[A-Za-z0-9._-]{1,200}$/

/** Only media the whiteboard can display; everything else is refused. */
export function isAllowedContentType(contentType: string | undefined): contentType is string {
  return Boolean(contentType && /^(image\/(png|jpeg|gif|webp|svg\+xml|avif)|video\/(mp4|webm|quicktime))$/.test(contentType))
}

export async function storeAsset(id: string, data: Buffer, contentType: string) {
  await mkdir(ASSETS_DIR, { recursive: true })
  await writeFile(join(ASSETS_DIR, id), data, { flag: 'wx' }) // never overwrite someone else's upload
  await writeFile(join(ASSETS_DIR, `${id}.meta.json`), JSON.stringify({ contentType }))
}

export async function loadAsset(id: string): Promise<{ data: Buffer; contentType: string } | null> {
  try {
    const [data, meta] = await Promise.all([readFile(join(ASSETS_DIR, id)), readFile(join(ASSETS_DIR, `${id}.meta.json`), 'utf8')])
    return { data, contentType: (JSON.parse(meta) as { contentType: string }).contentType }
  } catch {
    return null
  }
}
